console.log("--------------------------------------------------");
let salarioAbril = 5000;
// salarioAbril = salarioAbril + 3000;
salarioAbril += 3000;
console.log("O salário de Abril é: ", salarioAbril);
console.log("--------------------------------------------------");
let salarioMaio = 7000;
salarioMaio = salarioMaio - 2000;
salarioMaio -= 2000;
console.log("Salario de Maio é: ", salarioMaio);
console.log("--------------------------------------------------");